name: deploy
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd liviabot; git pull; yarn; tsc; pm2 restart livia;
